### ISSUE TITLE
Dont send If-None-Match tag

### ISSUE THREAD

**Issue by rimlin** [shaungrady/angular-http-etag#81] opened 2017-02-09 16:42 UTC
I meet the problem: requests are not supplied `If-None-Match` and instead `GET` Request Method set `OPTIONS`.
Here the Request Headers:
```
OPTIONS ... HTTP/1.1
Host: ...
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: GET
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Access-Control-Request-Headers: if-none-match
Accept: */*
Referer: http://localhost:3000
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
X-Compress: null
```

I see, what module was append `Access-Control-Request-Headers` and `Access-Control-Request-Method`, but originally Request Method is `OPTIONS` and `If-None-Match` field is not exist.

My configuration: 

```    
// Configure cache
httpEtagProvider
      .defineCache('persistentCache', {
        cacheService: 'localStorage'
})

...

$http.get(url,  {
        etagCache: 'persistentCache'
    })
    .success(function(data, status, headers, config, itemCache) {
        itemCache.set(data)
        resolve(data);
    })
    .cached(function (data, status, headers, config, itemCache) {
        let cachedData = itemCache.get();
        resolve(cachedData);
    })
```

My use:
angular-http-etag@2.0.16
angular@1.5.8

**Comment by shaungrady** [comment] 2017-02-10 17:01
Check the server's response headers. Is the server sending the `ETag` header? If it's not, then this module will not work.

![ETag Header](https://cloud.githubusercontent.com/assets/52413/22835962/7e1435d2-ef6f-11e6-837f-1bcf350b5104.png)

**Comment by rimlin** [comment] 2017-02-10 19:47
Yes, server send `ETag` header. Example of server response:

```
HTTP/1.1 200 OK
Cache-Control: must-revalidate, max-age=1200
Content-Length: 1551
Content-Type: application/json; charset=utf-8
ETag: "OYcnjQwnSHTMU2Mnd/Jx1Q==aAylqo6+aN+eMA3QeMSlTQ=="
Server: Microsoft-IIS/8.5
Link: 
x-volume-version: 1.0.108.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link, ETag
Date: Fri, 10 Feb 2017 19:36:53 GMT
```

Also, module for caching work fine, problem is what he modify `Request Method` and dont send `If-None-Match` header. In my case server cannot handle `OPTIONS` Request Method and return status `405` without ETag header and any content, but i can use cached copy.

**Comment by shaungrady** [comment] 2017-02-10 20:37
Sorry rimlin, I'm having trouble understanding. Are you saying you want support for the HTTP `OPTIONS` method? Like this?

``` javascript
$http({
  url: url,
  method: 'OPTIONS',
  etagCache: 'persistentCache'
})
```

**Comment by rimlin** [comment] 2017-02-11 07:39
Nope, i mean, what module modify HTTP Method to `OPTIONS`, but i make `GET` and need, what request will be `GET`. Also, he not supply headers `If-None-Match` tag.

What i do:
```
$http.get(url,  {
        etagCache: 'persistentCache'
    })
```

My request headers: 
```
OPTIONS ... HTTP/1.1
Host: ...
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: GET
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Access-Control-Request-Headers: if-none-match
Accept: */*
Referer: http://localhost:3000
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
X-Compress: null
```

I not sure, maybe is related problem with angular, but module not set `If-None-Match` tag...

**Comment by shaungrady** [comment] 2017-02-11 07:47
`angular-http-etag` does not work with `OPTIONS` requests. That is why there is no `If-None-Match`.

I do not know why your `GET` requests are changing to `OPTIONS` requests. There must be something else in your Angular app that is causing problems. There is nothing in `angular-http-etag` that would make `GET` change to `OPTIONS`.

**Comment by shaungrady** [comment] 2017-02-11 07:54
Take a look at this: http://stackoverflow.com/questions/12111936/angularjs-performs-an-options-http-request-for-a-cross-origin-resource#12112294

Is there a GET request made after the OPTIONS request? What is the server response to the OPTIONS request?

**Comment by rimlin** [comment] 2017-02-11 08:06
Hm, if `angular-http-etag` dont change HTTP to `OPTIONS` i need to check my app.. Why i ask here is because what when requests are not cached by `angular-http-etag` and sending at first time, HTTP Method is `GET` and all fine. But, when requests made second time, requests supply `OPTIONS` HTTP method and is not the problem of app or server, because if i remove `angular-http-etag` all requests will be sending with `GET` HTTP method.
I cannot change server logic, and in my case server cannot handle `OPTIONS` HTTP method and return `405 Method Not Allowed` and custom message about this..

**Comment by shaungrady** [comment] 2017-02-11 16:32
It's a "preflight" request and it's being sent by your web browser, not by Angular: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

It's caused by the fact that you're performing a cross-origin request. I think the only solution you might be able to implement is to proxy requests from your server to the remote server, so the browsers doesn't know it's cross-origin.

Closing this issue because it's not directly related to this project. Investigating this issue taught me a bit more about CORS though! 👍

**Closed by shaungrady** 2017-02-11 16:32 UTC

**Comment by shikharchauhan** [comment] 2017-11-28 07:37
Hi Shaun, 
could you help me with similar issue. no 304 is coming as expected. here are my code snippets.
config(function (httpEtagProvider) {
	httpEtagProvider
	.defineCache('persistentCache', {
		cacheService: 'localStorage'
	});
...... then
getDataByUrl = function (url, params) {
			return $http.get(host + url, {params: params, cache: cache,etagCache: 'persistentCache'});
		};
...... then
getDataByUrl(subHttp, params).success(function (data, status, headers, config, itemCache) {
				itemCache.set(data);
				d.resolve(data);
			}).cached(function (data, status, headers, config, itemCache) {
				var cachedData = itemCache.get();
				d.resolve(cachedData);
			}).error(function (error) {
				d.reject(error);
			});

am i missing something in order to get this done. thanks!

**Comment by shaungrady** [comment] 2017-11-28 16:34
Remove `cache: cache,` from
``` javascript
			return $http.get(host + url, {params: params, cache: cache,etagCache: 'persistentCache'});
```
